apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hpa
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: img-app-go
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 300m
        ports:
        - containerPort: 80
  
---

  apiVersion: v1
  kind: Service
  metadata:
    name: go-hpa
  spec:
    type: LoadBalancer
    ports:
      - port: 80
    selector:
      app: go-hpa
  
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:  #Faz referencia ao deployment
    apiVersion: apps/v1
    kind: Deployment
    name: go-hpa #nome do deployment no GCP
  targetCPUUtilizationPercentage: 15
      